//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEndProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public Nullable<int> comment_user_id { get; set; }
        public string comment_text { get; set; }
        public Nullable<int> comment_news_id { get; set; }
        public Nullable<System.DateTime> comment_date { get; set; }
    
        public virtual News News { get; set; }
        public virtual User User { get; set; }
    }
}
